root: true
parser: 'typescript-eslint-parser'
parserOptions:
  sourceType: 'module'
rules:
  semi: ['error', 'always']
  quotes: ['error', 'single']
  comma-dangle: ['error', {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      functions: 'always-multiline'
  }]