sudo: false
notifications:
  email: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '9'
  - '8'
script:
  - yarn test
  - yarn build
after_success:
  - yarn semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/